# Generated by Django 4.0.4 on 2022-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='adfaf'),
        ),
    ]
