# Generated by Django 4.0.6 on 2022-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'Экзэмляры книжечек'},
        ),
        migrations.AlterModelOptions(
            name='classv1',
            options={'verbose_name': 'Anime'},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.genre', verbose_name='Genre(Жанр)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='(This is help_text a field) Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200, verbose_name='Название жанра'),
        ),
    ]
