# Generated by Django 4.0.6 on 2022-07-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_bookinstance_options_alter_classv1_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassV1',
        ),
    ]
