# Generated by Django 4.0.6 on 2022-07-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_book_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(to='catalog.language', verbose_name='Язык'),
        ),
    ]
